Repository aravindvnair99/C, pull requests merged in 2020-10, with the labels that each got.

#19 IMPROVE THE DOCS
  Theory/Data types.md
Labels: Hacktoberfest

#18 Pascal Triangle
  pascal triangle.c
Labels: Hacktoberfest, size/S

#21 Create program to Concatenate two string
  Source Codes/Concatenate two string.c
Labels: Hacktoberfest, size/S

#22 palindrome pyramid pattern
  palindrome_pyramid_pattern.c
Labels: size/S
